[package]
name = "wgpurenderer"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "27.0"
glfw = { version = "0.60", features = ["raw-window-handle-v0-6"] }
pollster = "0.4"
env_logger = "0.11"
log = "0.4"
glam = { version = "0.29", features = ["bytemuck"] }
bytemuck = { version = "1.21", features = ["derive"] }
smallvec = "1.15"
sorted-vec = "0.8"
nohash-hasher = "0.2"
